server:
  port: 8011
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/firstmetcs/config-repo
          search-paths: examine
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    # 配置使用主机名注册服务
    # hostname: firstmetcs.com
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"